<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\WindowsDriverCore\WindowsDriverCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Interop.UIAutomationClient" Version="10.19041.0" />
  </ItemGroup>
</Project>
